-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [rolling_hash_kernel]: function definitions
import Aeneas
import RollingHashKernel.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

namespace RollingHashKernel

/-- [rolling_hash_kernel::MOD]
    Source: 'src/lib.rs', lines 3:0-3:35 -/
@[global_simps, irreducible]
def MOD : Result Std.U64 := do let i ← 1#u64 <<< 61#i32
                               i - 1#u64

/-- [rolling_hash_kernel::BASE]
    Source: 'src/lib.rs', lines 4:0-4:26 -/
@[global_simps, irreducible] def BASE : Std.U64 := 257#u64

/-- [rolling_hash_kernel::fast_mod]:
    Source: 'src/lib.rs', lines 6:0-13:1 -/
def fast_mod (x : Std.U128) : Result Std.U64 := do
  let i ← MOD
  let i1 ← lift (UScalar.cast .U128 i)
  let i2 ← lift (x &&& i1)
  let i3 ← x >>> 61#i32
  let i4 ← i2 + i3
  let res ← lift (UScalar.cast .U64 i4)
  if res >= i
  then res - i
  else ok res

/-- [rolling_hash_kernel::power_shift]: loop body 0:
    Source: 'src/lib.rs', lines 19:4-22:5 -/
@[rust_loop_body]
def power_shift_loop.body
  (exp : Std.Usize) (cur : Std.U128) (i : Std.Usize) :
  Result (ControlFlow (Std.U128 × Std.Usize) Std.U128)
  := do
  if i < exp
  then
    let i1 ← lift (UScalar.cast .U128 BASE)
    let i2 ← cur * i1
    let i3 ← fast_mod i2
    let cur1 ← lift (UScalar.cast .U128 i3)
    let i4 ← i + 1#usize
    ok (cont (cur1, i4))
  else ok (done cur)

/-- [rolling_hash_kernel::power_shift]: loop 0:
    Source: 'src/lib.rs', lines 19:4-22:5 -/
@[rust_loop]
def power_shift_loop
  (exp : Std.Usize) (cur : Std.U128) (i : Std.Usize) : Result Std.U128 := do
  loop
    (fun (cur1, i1) => power_shift_loop.body exp cur1 i1)
    (cur, i)

/-- [rolling_hash_kernel::power_shift]:
    Source: 'src/lib.rs', lines 16:0-24:1 -/
def power_shift (exp : Std.Usize) : Result Std.U64 := do
  let cur ← power_shift_loop exp 1#u128 0#usize
  ok (UScalar.cast .U64 cur)

/-- [rolling_hash_kernel::extend_right]:
    Source: 'src/lib.rs', lines 26:0-31:1 -/
def extend_right
  (hash : Std.U64) (right_hash : Std.U64) (right_length : Std.Usize) :
  Result Std.U64
  := do
  let ps ← power_shift right_length
  let result ← lift (UScalar.cast .U128 hash)
  let i ← lift (UScalar.cast .U128 ps)
  let i1 ← result * i
  let i2 ← lift (UScalar.cast .U128 right_hash)
  let result1 ← i1 + i2
  fast_mod result1

/-- [rolling_hash_kernel::append_right]:
    Source: 'src/lib.rs', lines 33:0-35:1 -/
def append_right (hash : Std.U64) (right_char : Std.U8) : Result Std.U64 := do
  let i ← lift (UScalar.cast .U64 right_char)
  extend_right hash i 1#usize

/-- [rolling_hash_kernel::hash_bytes]: loop body 0:
    Source: 'src/lib.rs', lines 40:4-43:5 -/
@[rust_loop_body]
def hash_bytes_loop.body
  (data : Slice Std.U8) (hash : Std.U64) (i : Std.Usize) :
  Result (ControlFlow (Std.U64 × Std.Usize) Std.U64)
  := do
  let i1 := Slice.len data
  if i < i1
  then
    let i2 ← Slice.index_usize data i
    let hash1 ← append_right hash i2
    let i3 ← i + 1#usize
    ok (cont (hash1, i3))
  else ok (done hash)

/-- [rolling_hash_kernel::hash_bytes]: loop 0:
    Source: 'src/lib.rs', lines 40:4-43:5 -/
@[rust_loop]
def hash_bytes_loop
  (data : Slice Std.U8) (hash : Std.U64) (i : Std.Usize) : Result Std.U64 := do
  loop
    (fun (hash1, i1) => hash_bytes_loop.body data hash1 i1)
    (hash, i)

/-- [rolling_hash_kernel::hash_bytes]:
    Source: 'src/lib.rs', lines 37:0-45:1 -/
@[reducible]
def hash_bytes (data : Slice Std.U8) : Result Std.U64 := do
  hash_bytes_loop data 0#u64 0#usize

end RollingHashKernel
