[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lean-hello"
version = "0.1.0"
description = "Tiny Python package powered by a Lean executable"
readme = "README.md"
requires-python = ">=3.12"
authors = [{ name = "Oscar Laird" }]

[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
lean_hello = ["bin/lean_hello_bin"]
