-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [adder_core]: function definitions
import Aeneas
import AdderCore.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

namespace RustAdder

/-- [adder_core::add_u32]:
    Source: 'adder_core/src/lib.rs', lines 3:0-5:1 -/
def add_u32 (x : Std.U32) (y : Std.U32) : Result Std.U32 := do
  ok (core.num.U32.wrapping_add x y)

/-- [adder_core::is_even]:
    Source: 'adder_core/src/lib.rs', lines 7:0-9:1 -/
def is_even (x : Std.U32) : Result Bool := do
  let i ← x % 2#u32
  ok (i = 0#u32)

end RustAdder
