[package]
name = "frontend"
version = "0.1.0"
authors = ["Oscar <olaird25@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bayesian = { version = "0.1.0", path = "../bayesian" }
dioxus = { version = "0.7.1", features = [] }
futures-util = "0.3.32"
layout = { version = "0.1.0", path = "../layout" }
rand = "0.10.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
statrs = "0.18.0"
tokio = { version = "1.52.1", features = ["macros", "rt-multi-thread", "sync", "time"] }
tokio-tungstenite = "0.29.0"

[features]
default = ["desktop"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
