name = "trieproof"
version = "0.1.0"
defaultTargets = ["trieproof"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.28.0"

[[lean_lib]]
name = "Trie"

[[lean_exe]]
name = "trieproof"
root = "Main"
